### ISSUE TITLE
咳咳…咳咳咳…嗯

### ISSUE THREAD

**Issue by sysfox** [RimoChan/unvcode#10]
咳咳咳咳…咳咳咳…嗯…嗯？？？！！！
![0AAACF20-E0FF-4934-BC9E-EB012A17A19E](https://user-images.githubusercontent.com/99103591/179916950-72a6955b-c536-4f92-8d9f-a24d82ace8f1.jpeg)

**Comment by Ges0ng** [comment]
我常常因为不够变态跟你们格格不入

**Comment by yyt6801** [comment]
star密码了，属于是
